# https://jekyllrb.com/docs/configuration/

# site-wide variables
title: Chantarachot Lab # title of site, used in tab name and elsewhere
email: t.chantarachot@gmail.com # default email
google: Thanin Chantarachot # default name to search on Google Scholar
github: tchantarachot # default GitHub user/org, without the @
twitter: tchantarachot # default Twitter handle, without the @
# instagram: fakeinstagramhandle # default Instagram handle, without the @
# youtube: fakeyoutubechannel # default YouTube channel handle

# base directory where site is hosted
# set to "" if hosting at a custom domain, eg yoursite.com
baseurl: /chantarachot-lab

# default front matter parameters for markdown files
# defaults can be overridden on a particular page, eg:
# ---
# description: Description unique to this page
# background: images/different-bg-for-this-page.jpg
# ---
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: Dr.Thanin Chantarachot Laboratory at Chulalonkorn Univeristy, Bangkok, Thailand.  # description that will show under search engine results
      background: images/IMG_8902.jpg # background image in header and footer
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
